[build]
  publish = "static"
  command = "yarn build"

[build.environment]
NODE_VERSION = "14"

[functions]
  directory = "functions"

[functions."ssr"]
  included_files = [
    "middleware.config.js",
    ".nuxt/**",
    "node_modules/@storefront-ui/**",
    "node_modules/@nuxt/ufo/**",
    "node_modules/@vue/composition-api/**",
    "node_modules/axios/**",
    "node_modules/follow-redirects/**",
    "node_modules/body-scroll-lock/**",
    "node_modules/@vue-storefront/**",
    "node_modules/vue-scrollto/**",
    "node_modules/nuxt-i18n/**",
    "node_modules/cookie-universal-nuxt/**"
    ]

[[redirects]]
  from = "spryker/*"
  to = "/.netlify/functions/middleware"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
